name: Test Continue/Skip Behavior
on:
  workflow_dispatch:
    inputs:
      skip_job1:
        type: boolean
        default: false
jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip_job1 }}
    steps:
      - run: echo job1
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo job2 $$ echo ${{ needs.job1.result }}
  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo job3
  job4:
    runs-on: ubuntu-latest
    needs:
      - job2
      - job3
    steps:
      - run: echo job4 && echo ${{ needs.job2.result }} && echo ${{ needs.job3.result }}
