name: Test Continue/Skip Behavior
on:
  workflow_dispatch:
    inputs:
      skip_job1:
        type: boolean
        default: false
      fail_job2:
        type: boolean
        default: false
jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip_job1 }}
    steps:
      - run: echo job1
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ always() && contains(fromJSON('["success", "skipped"]'), needs.job1.result) }}
    steps:
      - run: echo job2 && echo ${{ needs.job1.result }}
      - if: ${{ inputs.fail_job2 }}
        run: exit 1
  job3:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ always() && contains(fromJSON('["success", "skipped"]'), needs.job1.result) }}
    steps:
      - run: echo job3
  job4:
    runs-on: ubuntu-latest
    needs:
      - job2
      - job3
    if: ${{ always() && (needs.job2.result == 'success') && (needs.job3.result == 'success') }}
    steps:
      - run: echo job4 && echo ${{ needs.job2.result }} && echo ${{ needs.job3.result }}
