name: Download uploaded build artifact by name
on:
  workflow_dispatch:
    inputs:
      name:
        description: Artifact name
        type: string
        required: true
      branch:
        description: Branch name
        type: string
        default: 'master'
jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - id: download
        uses: dawidd6/action-download-artifact@v2
        with:
          branch: ${{ inputs.branch }}
          name: ${{ inputs.name }}
      - name: Display structure of downloaded files
        run: ls -R
