name: Download uploaded build artifact by name
on:
  workflow_dispatch:
    inputs:
      name:
        description: Artifact name
        type: string
        required: true
      commit:
        description: Full SHA of the commit of the run that uploaded artifact.
        type: string
        required: true
jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - id: download
        uses: dawidd6/action-download-artifact@v2
        with:
          commit: ${{ inputs.commit }}
          name: ${{ inputs.name }}
      - name: Display structure of downloaded files
        run: ls -R
