name: Input a matrix to run multiple jobs
on:
  workflow_dispatch:
    version_list:
      description: JSON list of Python versions to run the unit test with.
      type: string
      default: "{\"python_version\": [\"3.8\", \"3.9\"]}"
      required: true
jobs:
  unit-test:
    strategy:
      matrix: ${{ fromJson(inputs.version_list) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - run: echo "The Python version in this test is $(python -V)."
      - run: pip install pytest
      - run: PYTHONPATH=src pytest tests/
