name: Migrate DB with flyway
on: workflow_dispatch
jobs:
  migrate-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xueke477/flyway-migration@ee539c33f02876302397b04948c63a17a1a45333
        with:
          endpoint: ${{ secrets.MYSQL_ENDPOINT }}
          password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          locations: ${{ github.workspace }}/database/flywayfiles/sql
          defaultSchema: test_db
          schemas: test_db
