name: Migrate DB with flyway
on: workflow_dispatch
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo systemctl start mysql.service
  migrate-db:
    needs: prepare
    runs-on: ubuntu-latest
    container:
      image: "flyway/flyway:7.15"
      volumes:
        - ${{ github.workspace}}/database/flywayfiles/sql:/flyway/sql
        - ${{ github.workspace}}/database/flywayfiles/conf:/flyway/conf
    steps:
      - run: flyway -url=jdbc:mysql://127.0.0.1:3306?allowPublicKeyRetrieval=True -user=root -password=root -locations=filesystem:/flyway/sql/ -connectRetries=5 migrate
