name: Migrate DB with flyway
on:
  workflow_dispatch:
    inputs:
      mysql_root_password:
        description: Password of the root user.
        type: string
        required: true
      mysql_database:
        description: Default database to use.
        type: string
        required: true
jobs:
  migrate-db:
    needs: prepare
    runs-on: ubuntu-latest
    services:
      db:
        image: "xueke477/mysqlwithcmd:0.4.0"
        env:
          MYSQL_ROOT_PASSWORD: ${{ github.event.inputs.mysql_root_password }}
          MYSQL_DATABASE: ${{ github.event.inputs.mysql_database }}
        options: --entrypoint mysqld
    steps:
      - uses: actions/checkout@v2
      - uses: joshuaavalon/flyway-action@v2
        with:
          url: jdbc:mysql://db:3306?allowPublicKeyRetrieval=True
          user: root
          password: ${{ github.event.inputs.mysql_root_password }}
          locations: filesystem:/flyway/sql/
      - run: echo 'testing'
