name: Migrate DB with flyway
on:
  workflow_dispatch:
    inputs:
      mysql_database:
        description: Default database to use.
        type: string
        default: 'test_db'
jobs:
  migrate-db:
    runs-on: ubuntu-latest
    container:
      image: "flyway/flyway:7.15"
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - run: /flyway/flyway migrate -url=jdbc:mysql://${{ secrets.MYSQL_ENDPOINT }}:3306 -user=root -password=${{ secrets.MYSQL_ROOT_PASSWORD }} -locations="filesystem:$(pwd)/database/flywayfiles/sql" -defaultSchema=test_db -schemas='test_db'
