name: Migrate DB with flyway
on: workflow_dispatch
jobs:
  migrate-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xueke477/flyway-migration@609e8dded4f111aae380adcc7a5893ca4b97b4f3
        with:
          endpoint: ${{ secrets.MYSQL_ENDPOINT }}
          password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          locations: ${{ github.workspace }}/database/flywayfiles/sql
          defaultSchema: test_db
          schemas: test_db
