name: Pass secret values between steps
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # There should be no empty space in literal JSON string. Otherwise GHA fails to parse it.
      - run: SECRET="{\"a\":\"abc\"}" && echo "::add-mask::$SECRET" && echo "MY_VAR1=$SECRET" >> $GITHUB_ENV
      # Masked value appears as *** in GHA-generated logs, but it does show up in explicit echo.
      - run: echo ${{ env.MY_VAR1 }} && echo "::add-mask::${{ env.MY_VAR1.a }}"
      - run: echo ${{ fromJSON(env.MY_VAR1)['a'] }}
