name: Try PR trigger
on:
  pull_request
jobs:
  show-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ github.ref }} && echo ${{ github.head_ref }}
      - run: cat test.txt
      - run: cat src/mod1.py
