name: Build Lambda on ARM64 and upload to S3
on: workflow_dispatch
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.OIDC_IAM_ROLE }}
          aws-region: us-east-1
      # sam build 
      - run: whoami
      - run: python -V
      - run: sam build --use-container
      - run: RANDOM_HASH=$(python $GITHUB_WORKSPACE/scripts/generate_hash.py)
      - run: cd $GITHUB_WORKSPACE/.aws-sam/build/HelloWorldFunction && zip -r $GITHUB_WORKSPACE/build-${RANDOM_HASH}.zip .
      - run: cd $GITHUB_WORKSPACE
      - run: aws s3 cp $GITHUB_WORKSPACE/build-${RANDOM_HASH}.zip s3://xueke477-test-cicd-artifacts
