name: Build Lambda on ARM64 and upload to S3
on: workflow_dispatch
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # sam build 
      - run: sam build --use-container
      - run: pushd $GITHUB_WORKSPACE/.aws-sam/build/HelloWorldFunction
      - run: zip -r $GITHUB_WORKSPACE/build.zip .
      - run: popd
      - run: aws s3 cp $GITHUB_WORKSPACE/build.zip s3://xueke477-test-cicd-artifacts
