name: Test Cross-Architecture on GHA
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install qemu binfmt-support qemu-user-static
      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run: docker run --rm --platform linux/arm64/v8 --entrypoint=sam public.ecr.aws/sam/build-python3.8:latest-arm64 --help
