name: Test Cross-Architecture on GHA
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: docker run --rm -t arm64v8/ubuntu uname -m
