name: Test GHA Basics - 3
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # - run: echo "MY_VAR1={\"a\": \"abc\"}" >> $GITHUB_ENV
      - run: echo ${{ fromJSON(github).ref }}
