name: Unit test using poetry
on: workflow_dispatch
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache poetry installation
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/pipx/**
          key: ${{ github.ref_name }}-
      - name: Install poetry if cache misses
        if: ${{ steps.cache-poetry.outputs.cache-hit != 'true' }}
        run: PIPX_HOME=$GITHUB_WORKSPACE/pipx pipx install poetry
      - run: echo "$GITHUB_WORKSPACE/pipx/venvs/poetry/bin" >> $GITHUB_PATH
      - run: which poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
          cache: 'poetry'
      - run: echo "cache hit - ${{ toJSON(steps.cache-poetry.outputs.cache-hit) }}"
      - run: poetry install
      - run: PYTHONPATH=src poetry run pytest tests/
