name: Unit test using poetry
on: workflow_dispatch
jobs:
  build-upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.6' 
      - run: whoami && python -V && echo $HOME
      - run: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      - run: echo "~/.local/bin:~/.poetry/bin" >> $GITHUB_PATH
      - run: poetry --version
      - run: poetry install
      - run: PYTHONPATH=src poetry run pytest tests/unit
