name: Unit test using poetry
on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/**.py'
      - 'tests/**.py'
  workflow_dispatch:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache poetry installation
        id: cache-poetry
        if: ${{ always() }}
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/pipx/venvs/poetry/**
          key: master-branch-poetry-cache-small
      - name: Install poetry if cache misses
        if: ${{ steps.cache-poetry.outputs.cache-hit != 'true' }}
        run: PIPX_HOME=$GITHUB_WORKSPACE/pipx pipx install poetry
      - run: echo "$GITHUB_WORKSPACE/pipx/venvs/poetry/bin" >> $GITHUB_PATH
      - if: ${{ always() }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
          cache: 'poetry'
      - run: poetry install
      - run: PYTHONPATH=src poetry run pytest tests/ --cov=src --cov-report html:cov_html > unit-test-output.txt
      - name: Upload coverage report
        if: ${{ always() }}
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: coverage-${{ github.run_id }}
          path: ${{ github.workspace }}/cov_html/
      - name: Display test report
        if: ${{ always() }}
        run: cat unit-test-output.txt
      - name: Upload test report
        if: ${{ always() }}
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: unit-test-output-${{ github.run_id }}
          path: ${{ github.workspace }}/unit-test-output.txt
