name: Unit test using poetry
on: workflow_dispatch
jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.6' 
      - run: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      - run: echo "~/.poetry/bin" >> $GITHUB_PATH
      - run: poetry install
      - run: PYTHONPATH=src poetry run pytest tests/
