name: Unit test using poetry
on: workflow_dispatch
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache poetry installation
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: |
            '.local/pipx/venvs/poetry/**'
            '.local/bin/poetry'
          key: ${{ github.ref_name }}-${{ hashFiles('.local/pipx/venvs/poetry/**', '.local/bin/poetry') }}
      - name: Install poetry if cache misses
        if: ${{ steps.cache-poetry.outputs.cache-hit != 'true' }}
        run: pipx install poetry
      - run: which poetry
      - run: ls .local/bin && ls .local/pipx && ls .local/pipx/venvs && ls .local/pipx/venvs/poetry
      - run: ls -R .local/pipx/venvs/peotry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
          cache: 'poetry'
      - run: echo "cache hit - ${{ toJSON(steps.cache-poetry.outputs.cache-hit) }}"
      - run: poetry install
      - run: PYTHONPATH=src poetry run pytest tests/
