name: Upload Release
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
permissions:
  contents: write
jobs:
  unit-test:
    uses: ./.github/workflows/unit-test.yml
  upload-release:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v3
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag }}
          target_commitish: master
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: README.md
